trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '845a8593-869b-41f9-b08f-76be4c627b8c'
  imageRepository: 'callemaivitrine'
  containerRegistry: 'callem.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build_Docker
    displayName: Build Docker
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

# Added Test stage
- stage: Test
  displayName: Run Tests
  jobs:
  - job: Run_Tests
    displayName: Run Tests
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        echo "Installing dependencies..."
        npm install  # Added step to install dependencies
      displayName: 'Install Dependencies'

    - script: |
        echo "Running tests..."
        npm test  # Added step to run tests
      displayName: 'Run Tests'

- stage: Deploy
  displayName: Deploy to dev 
  jobs:
  - job: Deploy_dev
    displayName: Deploy to dev
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Abonnement Azure 1(dc49dc53-2c41-49b0-997d-53b5a99ae104)'
        appType: 'webAppContainer'
        WebAppName: 'callem-ai-vitrine'
        DockerNamespace: 'callem.azurecr.io'
        DockerRepository: $(imageRepository)
        DockerImageTag: $(Build.BuildId)
